on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    
    image: markhobson/maven-chrome
 
    stages:
      - test
 
    variables:
      MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
 
    test:
     stage: test
    allow_failure: true
 
    steps:
# Run the tests  
     - name: Build with Maven
       run:
     - mvn $MAVEN_OPTS clean package
     - mvn compile test
 
# Store artifacts
    artifacts:
    when: always
    name: "report"
    paths:
    - target/surefire-reports/*
    expire_in: 1 h
